name: 不具合報告
description: コメントが表示されない、機能が正しく動作していないなどの問題を報告
labels: ['不具合']
body:
  - type: input
    id: version
    attributes:
      label: バージョン
      description: |
        NCOverlayのバージョン
        ポップアップの `設定 > 情報` の `NCOverlay` の右側に記載されています
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - macOS
        - Linux
        - ChromeOS
        - Android

  - type: dropdown
    id: browser
    attributes:
      label: ブラウザ
      options:
        - Chrome
        - Edge
        - Firefox

  - type: checkboxes
    id: vods
    attributes:
      label: 動画配信サービス
      options:
        - label: dアニメストア
        - label: ABEMA
        - label: バンダイチャンネル
        - label: DMM TV
        - label: U-NEXT
        - label: FOD
        - label: Prime Video
        - label: Netflix
        - label: Hulu
        - label: ニコニコ動画
        - label: NHKプラス
        - label: TVer

  - type: textarea
    id: video
    attributes:
      label: 該当の動画
      description: タイトルやエピソード、URLなど

  - type: textarea
    id: description
    attributes:
      label: 詳細
    validations:
      required: true
